### PR TITLE
[Optimisation] Added mcpu option

### PR DESCRIPTION
**Pull request by hometue**
## Description
What feature/issue was addressed?
Added -mcpu option. This allows Clang to make optimisations to speed up the kernel. This looks to be an easy fix but I need to explain a little on why we optimise for Cortex A55, the Little core of the Snapdragon 865.

Firstly, we need to keep in mind our compiler is Clang, not GCC. GCC has the option to optimise for a Big.Little configuration, Clang sort of has but not really. So we either pick to optimise for Cortex A77 or the A55. The version of Clang I have can optimise for Cortex A55, so we just pick that?

Not really. I had to figure out how Clang optimises for both, so that we don't cause a performance regression in the Big core by performing optimisation on the little core. I had to dig through the sources to happy conclude that the optimisations are largely similar, any differences will not cause a regression.

In addition, custom kernels mostly set this too. So there is that too.

So with this magic sauce added, what should we expect? System responsiveness in general should improve. we should also see a general improve in performance in every aspect of the phone. We will have to test this of course. However I don't expect to see changes in how responsive CPU/GPU intensive tasks are, since their performance is mostly independent of the performance of the kernel.

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Type of change
- [x] Optimization (change optimizes kernel and not expected to change behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Others:

# Checklist
- [ ] I have not cleaned up my code. Forgive the minor errors
- [x] I have performed a self-review of my own code. Feel free to destroy my PR
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by hometue** [comment]
@MelvinFMQ I don't know if it is just me, but the impact of this seems to be quite huge. I may make this a major release if I find that this has a noticable effect. (Basically try to roll out to all robots)

**Review by MelvinFMQ — APPROVED** [review]
LGTM!

@hometue should do some benchmarking to track how much better it is + stability to check if there is any issues with reliability. 

can test on your device first.

**Comment by hometue** [comment]
Ok. Reliability wise there should be 0 problems, since this isn't like turning on an -O switch but more of tuning the output for Cortex A55. Have booted and ran the tuned kernel for a bit so I expect 0 issues, will just test on robot to be safe

**Comment by hometue** [comment]
Tested. Data does not show decisive evidence to suggest that the change definitely helps, but does create a small performance difference of about 0.1% to 1% depending on what data you look at. However it is also possible these are just within variance. What I can confirm is that the change is stable. Given that I see no reason to not use this, since it theoretically improves performance.

**Pull request merged**
