### PR TITLE
[Breaking build] Fix a compilation error picked up by Clang 11.

### PR DESCRIPTION
**Pull request by hometue**
## Description
I will try to explain why we need to do this pull request. Firstly, why did this only break build in later Clang? I am really not sure. Maybe changes to compiler behavior, although I cannot pinpoint what change it is.

Why is this needed?
Well, it shouldn't, but a combination of flags made this a build breaking issue. They enabled -Wstrict-prototypes, which means all functions must declare their arguments explicitly, if it does not take an argument you need to specify by declaring it as foo(void). They then went to set strict prototypes as an error instead of a warning, so compilation will break because of this error.

**TLDR**: If the kernel source has a function declared without explicity stating its arguments, even if it would be void, it will fail.

FYI, for anyone still reading, the function literally just above it, which is very similar except for small changes gets it right. Oneplus kernel codebase is great isn't it?

## Type of change
- [ ] Optimization (change optimizes kernel and not expected to change behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Others: Fix build in Clang 11

# Checklist
- [ ] I have not cleaned up my code. Forgive the minor errors
- [x] I have performed a self-review of my own code. Feel free to destroy my PR
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by MelvinFMQ — APPROVED** [review]
Haha love the commentary.

**Comment by MelvinFMQ** [comment]
Previously, what compiler were you using?

**Comment by hometue** [comment]
Clang 8 originally, then 9. Made most of the development on 9, then recently shifted to 11. Looked through the release notes but could not find any reason why compile worked previously. By all means it should have still failed, unless Clang 8-9 didn't actually process the flags.

**Comment by hometue** [comment]
My guess is that the previous Clang versions may have not processed the flags properly. Would make sense, because the release notes I looked through doesn't talk about bug fixes, so perhaps this was not intentional to begin with. Anyway will proceed to merge.

**Pull request merged**
